
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-12
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-12
pull_requests: [{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-assignments-put","number":45,"title":"Bj assignments put","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/45"},{"author":{"id":"U_kgDODXgFtA","is_bot":false,"login":"yibinjiang04","name":""},"headRefName":"bj-assignments-post","number":44,"title":"bj - add post api for assignments and two tests that admins and instrâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/44"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"ja-assignments-delete-job","number":43,"title":"JA - Added DELETE job for assignments ","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/43"},{"author":{"id":"U_kgDOCvDUNQ","is_bot":false,"login":"TejTripathyUCSB","name":""},"headRefName":"tst-POSTPUTSectionFixes","number":40,"title":"TST - POST PUT SECTION FIX","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/40"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-coursestaff-remove-frontend","number":23,"title":"AlvinC - Adding Frontend Checkbox for CourseStaff Delete","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/23"}]
