
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-frontiers-f25-12
owner: ucsb-cs156-f25
repo_name: proj-frontiers-f25-12
pull_requests: [{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-help-downloadstudentcsv","number":38,"title":"AlvinC - Help Downloadstudentcsv","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/38"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-info-icon","number":31,"title":"Hrehwald info icon","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/31"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"help-text-csv","number":29,"title":"Added help documentation to explain how dropped students work","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/29"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"JaydenT-task-reintroduce-react-eslint-rules","number":28,"title":"updated eslint rules","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/28"},{"author":{"id":"U_kgDOC6IUpQ","is_bot":false,"login":"joshua-dev-codes","name":""},"headRefName":"refactor-sign-in-and-prompt","number":27,"title":"Refactored SignInPage and PromptSignInPage","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/27"},{"author":{"id":"U_kgDOCQQjrw","is_bot":false,"login":"AlvinLovesCode","name":""},"headRefName":"alvinc-coursestaff-remove-frontend","number":23,"title":"AlvinC - Adding Frontend Checkbox for CourseStaff Delete","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/23"},{"author":{"id":"U_kgDOCqFMyA","is_bot":false,"login":"jaytan3966","name":"Jayden Tan"},"headRefName":"JaydenT-UXImprovements","number":21,"title":"Sorted students by first name","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/21"},{"author":{"id":"U_kgDOBaYVeg","is_bot":false,"login":"HRehwald","name":"Hauke Rehwald"},"headRefName":"hrehwald-sanitize-email","number":14,"title":"hrehwald sanitize emails for backend","url":"https://github.com/ucsb-cs156-f25/proj-frontiers-f25-12/pull/14"}]
